main: de.netzguru0815.cropprotect.CropProtect

name: CropProtect
description: Alles rund um Pflanzen und Garten.

author: netzguru0815
website: Coming Soon!

version: 1.4.2 SNAPSHOT
api-version: 1.21


commands:
  cropprotect:
    description: Alle wichtigen Commands.
    usage: /<command> <version|reload>
    aliases: [ cp ]

permissions:
  cropprotect.command.reload:
    description: Allow the use of the '/cropprotect reload' subcommand
    default: op